//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollUsingJqueryUIWithValidation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Salary_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<double> Basic_Salary { get; set; }
        public Nullable<double> House_Rent { get; set; }
        public Nullable<double> Medical { get; set; }
        public Nullable<double> Conveyance { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
