//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PayrollUsingJqueryUIWithValidation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Employees = new HashSet<Employee>();
        }
        public int Department_Id { get; set; }

        [Required(ErrorMessage = "Code is required.")]
        [StringLength(10, MinimumLength = 2, ErrorMessage = "Please keep the Code between 2 and 3 character.")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Number must be a natural number")]
        [Remote("IsCodeExist", "Department", ErrorMessage = "This Code already Exits")]
        [Display(Name = "Code:")]
        public string Code { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        [StringLength(10, MinimumLength = 2, ErrorMessage = "Please keep the Code between 3 and 50 character.")]
        [RegularExpression("^([a-zA-Z0-9 .&'-]+)$", ErrorMessage = "Invalid First Name")]
        [Remote("IsNameExist", "Department", ErrorMessage = "This Code already Exits")]
        [Display(Name = "Name:")]
        public string Name { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
