//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollUsingJqueryUIWithValidation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_Id { get; set; }
        public string Transaction_No { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public int Employee_Id { get; set; }
        public int Year_ { get; set; }
        public string Month_ { get; set; }
        public double Total_Amount { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
